### ISSUE TITLE
unable to connect to RCON server

### ISSUE THREAD

**Issue by subyoung** [palworldlol/palworld-exporter#5]
I have already had palworld server running in docker and the RCON has enabled, but it could connect to the RCON. Oh my server is in the docker on macos(M1)

**Comment by bostrt** [comment]
Can you share the error you are seeing? And, a few more questions:

- Are the palworld-exporter and palworld-server on the same container network?
- If you are using docker-compose can you share it?

**Comment by subyoung** [comment]
Thank you for replying.
As you can see, I can connect to the RCON server by using rcon-cli
<img width="562" alt="image" src="https://github.com/palworldlol/palworld-exporter/assets/51379801/4320e3fc-70ac-4f45-8be5-aad8b4527681">

- They are under different volumes. Does it mean it could not connect to the RCON host?
<img width="1332" alt="image" src="https://github.com/palworldlol/palworld-exporter/assets/51379801/2b1e566b-494c-4247-81af-c06cba3ba015">

- This is the error message
<img width="1144" alt="image" src="https://github.com/palworldlol/palworld-exporter/assets/51379801/68bc4adf-1137-42d6-9e63-bab09b1245cc">

- The docker-compose I used:
<img width="1033" alt="image" src="https://github.com/palworldlol/palworld-exporter/assets/51379801/973c9b98-3484-4916-a933-6d45c4c789e1">

**Comment by bostrt** [comment]
Closing but let me know if you have anymore questions.
